### ISSUE TITLE
Create documentation file

### ISSUE THREAD

**Issue by Sedfer** [demcry/Sort#22]

**Comment by Sedfer** [comment]
Create https://github.com/demcry/Sort/commit/bec01ea5bde752801c2a6d85c22d2c06de6ee0ba, but need more information in some sections

**Comment by Sedfer** [comment]
Update https://github.com/demcry/Sort/commit/131f301b4806ccd58a363297da30ede8b34f17e3.
  1. [x] ~~3. Programm description~~

Need to rewrite 
  1. [ ] 1. General description;
  2. [ ] 2. Detailed requirments;

Add sectios:
  1. [ ] 4. Testing

**Comment by demcry** [comment]
https://github.com/demcry/Sort/commit/037123e60f8e9bc488d44a2a7ce887f05e74ec1d
